In [1]:
# Aim:To perfrom simple linear regression and find out the coefficients of it.

In [2]:
# Name:Samruddhi Laddha 
# Roll No:44
# Section:A

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
import os 

In [5]:
os.getcwd()

'C:\\Users\\samru'

In [6]:
os.chdir("C:\\Users\\samru\\OneDrive\\Desktop")

In [7]:
df=pd.read_csv("CHD_preprocessed.csv")

In [8]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39          1              0         0.0     0.0                0   
1     0   46          0              0         0.0     0.0                0   
2     1   48          0              1        20.0     0.0                0   
3     0   61          1              1        30.0     0.0                0   
4     0   46          1              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [9]:
df.tail()

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
4128     1   50          0              1         1.0     0.0   
4129     1   51          1              1        43.0     0.0   
4130     0   48          0              1        20.0     0.0   
4131     0   44          0              1        15.0     0.0   
4132     0   52          0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
4128                0             1         0    313.0  179.0   92.0  25.97   
4129                0             0         0    207.0  126.5   80.0  19.71   
4130                0             0         0    248.0  131.0   72.0  22.00   
4131                0             0         0    210.0  126.5   87.0  19.16   
4132                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
4128       66.0     86.0           1  
4129       65.0     68.0           0  
4130       84.0     86.0           0  
4131       86.0     82.0           0  
4132       80.0    107.0           0

In [10]:
df.head(30)

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0      1   39          1              0         0.0     0.0                0   
1      0   46          0              0         0.0     0.0                0   
2      1   48          0              1        20.0     0.0                0   
3      0   61          1              1        30.0     0.0                0   
4      0   46          1              1        23.0     0.0                0   
5      0   43          0              0         0.0     0.0                0   
6      0   63          0              0         0.0     0.0                0   
7      0   45          0              1        20.0     0.0                0   
8      1   52          0              0         0.0     0.0                0   
9      1   43          0              1        30.0     0.0                0   
10     0   50          0              0         0.0     0.0                0   
11     0   43          0              0         0.0     0.0                0   
12     1   46          0              1        15.0     0.0                0   
13     0   41          1              0         0.0     1.0                0   
14     0   39          0              1         9.0     0.0                0   
15     0   38          0              1        20.0     0.0                0   
16     1   48          1              1        10.0     0.0                0   
17     0   46          0              1        20.0     0.0                0   
18     0   38          0              1         5.0     0.0                0   
19     1   41          0              0         0.0     0.0                0   
20     0   42          0              1        30.0     0.0                0   
21     0   43          0              0         0.0     0.0                0   
22     0   52          0              0         0.0     0.0                0   
23     0   52          1              1        20.0     0.0                0   
24     1   44          0              1        30.0     0.0                0   
25     1   47          1              1        20.0     0.0                0   
26     0   60          0              0         0.0     0.0                0   
27     1   35          0              1        20.0     0.0                0   
28     0   61          1              0         0.0     0.0                0   
29     0   60          0              0         0.0     0.0                0   

    prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0              0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1              0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2              0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3              1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4              0         0    285.0  130.0   84.0  23.10       85.0     85.0   
5              1         0    228.0  180.0  110.0  30.30       77.0     99.0   
6              0         0    205.0  138.0   71.0  33.11       60.0     85.0   
7              0         0    313.0  100.0   71.0  21.68       79.0     78.0   
8              1         0    260.0  141.5   89.0  26.36       76.0     79.0   
9              1         0    225.0  162.0  107.0  23.61       93.0     88.0   
10             0         0    254.0  133.0   76.0  22.91       75.0     76.0   
11             0         0    247.0  131.0   88.0  27.64       72.0     61.0   
12             1         0    294.0  142.0   94.0  26.31       98.0     64.0   
13             1         0    332.0  124.0   88.0  31.31       65.0     84.0   
14             0         0    226.0  114.0   64.0  22.35       85.0     82.0   
15             1         0    221.0  140.0   90.0  21.35       95.0     70.0   
16             1         0    232.0  138.0   90.0  22.37       64.0     72.0   
17             0         0    291.0  112.0   78.0  23.38       80.0     89.0   
18 

In [11]:
df[5:10]

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
5     0   43          0              0         0.0     0.0                0   
6     0   63          0              0         0.0     0.0                0   
7     0   45          0              1        20.0     0.0                0   
8     1   52          0              0         0.0     0.0                0   
9     1   43          0              1        30.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
5             1         0    228.0  180.0  110.0  30.30       77.0     99.0   
6             0         0    205.0  138.0   71.0  33.11       60.0     85.0   
7             0         0    313.0  100.0   71.0  21.68       79.0     78.0   
8             1         0    260.0  141.5   89.0  26.36       76.0     79.0   
9             1         0    225.0  162.0  107.0  23.61       93.0     88.0   

   TenYearCHD  
5           0  
6           1  
7           0  
8           0  
9           0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4133 entries, 0 to 4132
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4133 non-null   int64  
 1   age              4133 non-null   int64  
 2   education        4133 non-null   int64  
 3   currentSmoker    4133 non-null   int64  
 4   cigsPerDay       4133 non-null   float64
 5   BPMeds           4133 non-null   float64
 6   prevalentStroke  4133 non-null   int64  
 7   prevalentHyp     4133 non-null   int64  
 8   diabetes         4133 non-null   int64  
 9   totChol          4133 non-null   float64
 10  sysBP            4133 non-null   float64
 11  diaBP            4133 non-null   float64
 12  BMI              4133 non-null   float64
 13  heartRate        4133 non-null   float64
 14  glucose          4133 non-null   float64
 15  TenYearCHD       4133 non-null   int64  
dtypes: float64(8), int64(8)
memory usage: 516.8 KB


In [13]:
df.describe()

male          age    education  currentSmoker   cigsPerDay  \
count  4133.000000  4133.000000  4133.000000    4133.000000  4133.000000   
mean      0.427293    49.557222     0.280668       0.494798     9.101621   
std       0.494745     8.561628     0.449380       0.500033    11.918440   
min       0.000000    32.000000     0.000000       0.000000     0.000000   
25%       0.000000    42.000000     0.000000       0.000000     0.000000   
50%       0.000000    49.000000     0.000000       0.000000     0.000000   
75%       1.000000    56.000000     1.000000       1.000000    20.000000   
max       1.000000    70.000000     1.000000       1.000000    70.000000   

            BPMeds  prevalentStroke  prevalentHyp     diabetes      totChol  \
count  4133.000000      4133.000000   4133.000000  4133.000000  4133.000000   
mean      0.034358         0.006049      0.311154     0.025647   236.664408   
std       0.182168         0.077548      0.463022     0.158100    43.909188   
min       0.000000         0.000000      0.000000     0.000000   107.000000   
25%       0.000000         0.000000      0.000000     0.000000   206.000000   
50%       0.000000         0.000000      0.000000     0.000000   234.000000   
75%       0.000000         0.000000      1.000000     0.000000   262.000000   
max       1.000000         1.000000      1.000000     1.000000   600.000000   

             sysBP        diaBP          BMI    heartRate      glucose  \
count  4133.000000  4133.000000  4133.000000  4133.000000  4133.000000   
mean    132.367046    82.872248    25.778571    75.925236    81.946528   
std      22.080332    11.952654     4.074360    12.049188    22.860954   
min      83.500000    48.000000    15.540000    44.000000    40.000000   
25%     117.000000    75.000000    23.060000    68.000000    72.000000   
50%     128.000000    82.000000    25.380000    75.000000    80.000000   
75%     144.000000    89.500000    27.990000    83.000000    85.000000   
max     295.000000   142.500000    56.800000   143.000000   394.000000   

        TenYearCHD  
count  4133.000000  
mean      0.151948  
std       0.359014  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [14]:
df.shape

(4133, 16)

In [15]:
df.size

66128

In [16]:
df.ndim

2

In [17]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [18]:
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [19]:
x = np.arange(1,25).reshape(12,2)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])

In [20]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [21]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y) #test_size=.3, random_state=42)

In [24]:
y_train

array([0, 0, 1, 0, 1, 0, 1, 0, 0])

In [25]:
y_test

array([1, 1, 1])

In [26]:
x_train

array([[13, 14],
       [ 1,  2],
       [15, 16],
       [23, 24],
       [ 9, 10],
       [19, 20],
       [17, 18],
       [11, 12],
       [ 7,  8]])

In [27]:
x_test

array([[21, 22],
       [ 3,  4],
       [ 5,  6]])

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train,y_train)
model.score(x_train,y_train)

0.010000000000000009